### ISSUE TITLE
请问只支持白天黑夜 两种模式嘛

### ISSUE THREAD

**Issue by 1191102363** [qqliu10u/QSkinLoader#4]

**Comment by qqliu10u** [comment]
不是的，这是个换肤框架，支持切换多种皮肤，我做demo的例子里只写了白天夜间模式切换，是因为我比较懒，^_^。具体来讲：框架默认实现了两种换肤方式，分别为APKResourceLoader/SuffixResourceLoader和一种夜间模式切换方式ConfigChangeResourceLoader。

1）APKResourceLoader换肤的皮肤包是一个apk文件，支持从服务端或者本地路径中加载皮肤包；
2）SuffixResourceLoader支持定义不同名称的资源来换肤，比如文字颜色R.color.text_color默认为黑色，增加R.color.text_color_red并使用SuffixResourceLoader.loadResource("red",listener)可以替换为红色；
3）至于ConfigChangeResourceLoader，由于使用的是Android的夜间模式，所以只能切换两种模式。

PS：框架支持自定义皮肤加载方式，不使用这三种加载方式，不过一般情况下用途不大。

**Comment by fengtianyou** [comment]
可以自己扩充

**Comment by lmz1993** [comment]
请问如何支持fragment急急急！！！

**Comment by qqliu10u** [comment]
Fragment换肤请见：https://github.com/qqliu10u/QSkinLoader/issues/3
