### ISSUE TITLE
关于大量控件换肤

### ISSUE THREAD

**Issue by VeiZhang** [qqliu10u/QSkinLoader#5]
**当很多相同的控件需要换肤时，对于相同的控件每个都需要skin:enable="true"比较麻烦，有什么办法自定义控件，然后让它支持换肤呢？**

**Comment by qqliu10u** [comment]
不好意思，最近没怎么上线。
换肤是全局的操作，你这种情况应该不是只对某个类型的控件换肤吧？自定义View不好解决这个问题，我建议你直接去掉SkinAttributeParser.isSupportSkin内skin:enable判断。
这样好处是，你不用在代码里挨个增加skin:enable属性了，坏处是每个View的创建都会走代理View创建，解析属性，性能上会有点损失。

**Comment by VeiZhang** [comment]
对，我目前是修改了源码，添加skin:enable的控制，默认设置为true；因为需要换大量的控件，所以遇到不想换肤的控件设置skin:enable="false"
