### ISSUE TITLE
include标签换肤

### ISSUE THREAD

**Issue by VeiZhang** [qqliu10u/QSkinLoader#6]
发现使用include标签时切换皮肤，不能更换成功

**Comment by qqliu10u** [comment]
是的，这个问题我也发现了，但一直没有找到解决方法，问题原因是加载include标签的LayoutInflator实例和外层布局的实例并不一致。

**Comment by VeiZhang** [comment]
@qqliu10u 实在不行，那只能用常用的办法写include里的控件，只是为了方便复用。除了这个标签还有其他的不支持吗？

**Comment by qqliu10u** [comment]
常用的布局控件里就这个是不支持的，另外控件属性里面style也是不支持的。

**Comment by VeiZhang** [comment]
@qqliu10u 3Q
